language: node_js

node_js:
  - '14'
  - '13'
  - '12'
  - '10'

env:
  global:
    - TIMEOUT_MULTIPLIER=8
    
install:
  - npm ci

script:
  - npm test
  - >
    if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
      npm audit
      npm run coveralls
      rm -rf node_modules
      npm ci --only=production
      ./test/smoke-test.sh;
      ./test/entity-test.sh;
      ./test/joi-test.sh;
    fi
  

os:
  - "linux"
  - "osx"
  - "windows"
  
