language: node_js

node_js:
  - '14'
  - '13'
  - '12'
  - '10'

env:
  global:
    - TIMEOUT_MULTIPLIER=8
    
install:
  - npm ci

script:
  - npm test
  - npm audit
  - npm run coveralls
  - rm -rf node_modules
  - npm ci --only=production
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then ./test/smoke-test.sh; fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then ./test/entity-test.sh; fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then ./test/joi-test.sh; fi
  

os:
  - "linux"
  - "osx"
  - "windows"
  
